"""create tables

Revision ID: b4e18255bb7d
Revises: fbee6c221930
Create Date: 2022-03-15 23:00:50.245698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e18255bb7d'
down_revision = 'fbee6c221930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
